name: Publish Extension

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Package extension
        run: npm run package

      - name: Publish to VS Code Marketplace
        run: npx @vscode/vsce publish --packagePath dist/extension.vsix --pat ${{ secrets.AZURE_DEVOPS_TOKEN }}

    #   - name: Publish to Open VSX Registry
    #     run: npx ovsx publish dist/extension.vsix --pat "$OVSX_PAT"
    #     env:
    #       OVSX_PAT: ${{ secrets.OVSX_PAT }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Package extension
        run: npm run package

      - name: Create a release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.tagName.outputs.tag }}
          files: dist/extension.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
